spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/goryde_payment?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  cloud:
    openfeign:
      client:
        config:
          "RIDE-SERVICE":
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: basic

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
